/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulanceRoute: typeof AmbulanceRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CitizenRoute: typeof CitizenRoute
  CommandRoute: typeof CommandRoute
  HospitalRoute: typeof HospitalRoute
  LoginRoute: typeof LoginRoute
  TrackingRoute: typeof TrackingRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulanceRoute: AmbulanceRoute,
  AnalyticsRoute: AnalyticsRoute,
  CitizenRoute: CitizenRoute,
  CommandRoute: CommandRoute,
  HospitalRoute: HospitalRoute,
  LoginRoute: LoginRoute,
  TrackingRoute: TrackingRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
